version: "3"
environment:
services:
  db:
    image: ghcr.io/ferretdb/ferretdb:1.17.0
    user: 1001:1001
    environment:
      - FERRETDB_HANDLER=sqlite
    volumes:
      # You can use a directory-based volume here instead of a named one, if you prefer
      - dbvol:/state
    restart: unless-stopped
    networks:
      - internal
  app:
    image: uniferret:latest
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Singapore
      - FERRETDB_HANDLER=sqlite
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi_db
    volumes:
      - configvol:/config
    restart: unless-stopped
    networks:
      servernet:
        ipv4_address: IP_HERE
      internal:

networks:
  servernet:
    external: true
    name: servernet
  internal:

volumes:
  uniferret_dbvol:
    external: true
  uniferret_configvol:
    external: true