#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# create our folders
mkdir -p \
    /config/{data,logs}

# create symlinks for config
symlinks=( \
/usr/lib/unifi/data \
/usr/lib/unifi/logs )

for i in "${symlinks[@]}"; do
    if [[ -L "$i" && ! "$i" -ef /config/"$(basename "$i")"  ]]; then
        unlink "$i"
    fi
    if [[ ! -L "$i" ]]; then
        ln -s /config/"$(basename "$i")" "$i"
    fi
done

if [[ ! -e /config/data/system.properties ]]; then
    if [[ -z "${MONGO_HOST}" ]]; then
        echo "*** No MONGO_HOST set, cannot configure database settings. ***"
        sleep infinity
    else
        echo "*** Waiting for MONGO_HOST ${MONGO_HOST} to be reachable. ***"
        DBCOUNT=0
        while true; do
            if nc -w1 "${MONGO_HOST}" "${MONGO_PORT}" >/dev/null 2>&1; then
                break
            fi
            DBCOUNT=$((DBCOUNT+1))
            if [[ ${DBCOUNT} -gt 6 ]]; then
                echo "*** Defined MONGO_HOST ${MONGO_HOST} is not reachable, cannot proceed. ***"
                sleep infinity
            fi
            sleep 5
        done
        if [ "$FERRETDB_HANDLER" == "sqlite" ]; then
            MONGO_CREDENTIALS="" # No creds
        else
            MONGO_CREDENTIALS="$MONGO_USER:$MONGO_PASS@" # Ferret postgres or Mongo
        fi
        sed -i "s/~MONGO_CREDENTIALS~/${MONGO_CREDENTIALS}/" /defaults/system.properties

        sed -i "s/~MONGO_HOST~/${MONGO_HOST}/" /defaults/system.properties
        sed -i "s/~MONGO_PORT~/${MONGO_PORT}/" /defaults/system.properties
        sed -i "s/~MONGO_DBNAME~/${MONGO_DBNAME}/" /defaults/system.properties
        MONGO_ARGS="\\?tls="
        if [[ "${MONGO_TLS,,}" = "true" ]]; then
            MONGO_ARGS="${MONGO_ARGS}true"
        else
            MONGO_ARGS="${MONGO_ARGS}false"
        fi
        if [[ ! -z "${MONGO_AUTHSOURCE}" ]]; then
            MONGO_ARGS="${MONGO_ARGS}\\&authSource=${MONGO_AUTHSOURCE}"
        fi
        if [ "$FERRETDB_HANDLER" == "postgres" ]; then
            MONGO_ARGS="${MONGO_ARGS}\\&authMechanism=PLAIN"
        fi
        sed -i "s/~MONGO_ARGS~/${MONGO_ARGS}/" /defaults/system.properties
        cp /defaults/system.properties /config/data
    fi
fi

# generate key
if [[ ! -f /config/data/keystore ]]; then
    keytool -genkey -keyalg RSA -alias unifi -keystore /config/data/keystore \
    -storepass aircontrolenterprise -keypass aircontrolenterprise -validity 3650 \
    -keysize 4096 -dname "cn=unifi" -ext san=dns:unifi
fi

# permissions
lsiown -R abc:abc \
	/config \
	/run/unifi

lsiown abc:abc \
    /config/data/keystore
